# ============================================================================
# ðŸ“¦ PyPI Publish Action
# ============================================================================
# Reusable composite action for building and publishing Python packages to PyPI.
# Supports both PyPI and TestPyPI using Trusted Publishing (OIDC).
#
# Usage:
#   - uses: fulviofreitas/eero-api/.github/actions/pypi-publish@master
#     with:
#       version: "1.0.0"
#
# Requirements:
#   - Trusted Publisher configured on PyPI/TestPyPI
#   - Job must have `id-token: write` permission
#   - Job should use an environment (e.g., `pypi` or `testpypi`)
# ============================================================================

name: "ðŸ“¦ PyPI Publish"
description: "Build and publish Python package to PyPI using Trusted Publishing"

inputs:
  version:
    description: "Package version being published"
    required: true
  python-version:
    description: "Python version to use for building"
    required: false
    default: "3.12"
  repository-url:
    description: "PyPI repository URL (use https://test.pypi.org/legacy/ for TestPyPI)"
    required: false
    default: ""
  skip-existing:
    description: "Skip upload if version already exists"
    required: false
    default: "false"
  dry-run:
    description: "Build but don't upload"
    required: false
    default: "false"
  attestations:
    description: "Generate and upload attestations (requires additional setup)"
    required: false
    default: "false"

outputs:
  published:
    description: "Whether the package was published"
    value: ${{ steps.result.outputs.published }}
  package-name:
    description: "Name of the published package"
    value: ${{ steps.build.outputs.package-name }}

runs:
  using: "composite"
  steps:
    # ========================================================================
    # ðŸ Setup Python
    # ========================================================================
    - name: ðŸ Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # ========================================================================
    # ðŸ“¦ Install Build Tools
    # ========================================================================
    - name: ðŸ“¦ Install build tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    # ========================================================================
    # ðŸ—ï¸ Build Package
    # ========================================================================
    - name: ðŸ—ï¸ Build package
      id: build
      shell: bash
      run: |
        echo "ðŸ“¦ Building package..."
        python -m build
        
        # Extract package name from dist files
        WHEEL=$(ls dist/*.whl 2>/dev/null | head -1)
        if [ -n "$WHEEL" ]; then
          PACKAGE_NAME=$(basename "$WHEEL" | cut -d'-' -f1)
          echo "package-name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
          echo "âœ… Built: ${PACKAGE_NAME}"
        fi
        
        echo ""
        echo "ðŸ“ Build artifacts:"
        ls -la dist/

    # ========================================================================
    # ðŸ” Validate Package
    # ========================================================================
    - name: ðŸ” Validate package
      shell: bash
      run: |
        echo "ðŸ” Running twine check..."
        twine check dist/*
        echo "âœ… Package validation passed"

    # ========================================================================
    # ðŸ“¤ Publish to PyPI
    # ========================================================================
    # Publish to TestPyPI (when repository-url is specified)
    - name: ðŸ“¤ Publish to TestPyPI
      if: inputs.dry-run != 'true' && inputs.repository-url != ''
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.repository-url }}
        skip-existing: ${{ inputs.skip-existing }}
        attestations: ${{ inputs.attestations }}
        verbose: true

    # Publish to PyPI (default, when no repository-url)
    - name: ðŸ“¤ Publish to PyPI
      if: inputs.dry-run != 'true' && inputs.repository-url == ''
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: ${{ inputs.skip-existing }}
        attestations: ${{ inputs.attestations }}
        verbose: true

    # ========================================================================
    # ðŸ“Š Set Result
    # ========================================================================
    - name: ðŸ“Š Set result
      id: result
      shell: bash
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          echo "published=false" >> $GITHUB_OUTPUT
          echo "ðŸ§ª Dry-run mode - package not published"
        else
          echo "published=true" >> $GITHUB_OUTPUT
          echo "âœ… Package published successfully"
        fi

    # ========================================================================
    # ðŸ“ Generate Summary
    # ========================================================================
    - name: ðŸ“ Generate summary
      if: always()
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        PACKAGE_NAME="${{ steps.build.outputs.package-name }}"
        DRY_RUN="${{ inputs.dry-run }}"
        REPO_URL="${{ inputs.repository-url }}"
        
        # Determine target registry
        if [ -n "$REPO_URL" ] && [[ "$REPO_URL" == *"test.pypi"* ]]; then
          REGISTRY="TestPyPI"
          PACKAGE_URL="https://test.pypi.org/project/${PACKAGE_NAME}/"
          INSTALL_CMD="pip install -i https://test.pypi.org/simple/ ${PACKAGE_NAME}==${VERSION}"
        else
          REGISTRY="PyPI"
          PACKAGE_URL="https://pypi.org/project/${PACKAGE_NAME}/"
          INSTALL_CMD="pip install ${PACKAGE_NAME}==${VERSION}"
        fi
        
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## ðŸ“¦ ${REGISTRY} Publication
        
        EOF
        
        if [ "$DRY_RUN" = "true" ]; then
          cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        > [!NOTE]
        > ### ðŸ§ª Dry-Run Mode
        > Package was built but not published.
        
        EOF
        fi
        
        cat >> $GITHUB_STEP_SUMMARY << EOF
        | Property | Value |
        |:---------|:------|
        | ðŸ“¦ Package | \`${PACKAGE_NAME}\` |
        | ðŸ·ï¸ Version | \`${VERSION}\` |
        | ðŸŽ¯ Registry | ${REGISTRY} |
        
        EOF
        
        if [ "$DRY_RUN" != "true" ]; then
          cat >> $GITHUB_STEP_SUMMARY << EOF
        ### ðŸ“¥ Installation
        
        \`\`\`bash
        ${INSTALL_CMD}
        \`\`\`
        
        ðŸ”— [View on ${REGISTRY}](${PACKAGE_URL})
        
        EOF
        fi
        
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ### ðŸ“ Build Artifacts
        
        \`\`\`
        $(ls -la dist/)
        \`\`\`
        EOF
