# ============================================================================
# ðŸ“š Wiki Sync Action
# ============================================================================
# Reusable composite action for syncing wiki/ directory to GitHub Wiki.
#
# Usage:
#   - uses: fulviofreitas/eero-api/.github/actions/wiki-sync@master
#     with:
#       wiki-path: "wiki/"
# ============================================================================

name: "ðŸ“š Wiki Sync"
description: "Sync wiki directory to GitHub Wiki"

inputs:
  wiki-path:
    description: "Path to wiki directory"
    required: false
    default: "wiki/"
  ignore-file:
    description: "File with patterns to ignore"
    required: false
    default: ".gitignore"

outputs:
  synced:
    description: "Whether wiki was synced"
    value: ${{ steps.sync.outputs.synced }}

runs:
  using: "composite"
  steps:
    - name: ðŸ”„ Sync wiki
      id: sync
      uses: Andrew-Chen-Wang/github-wiki-action@v5
      with:
        path: ${{ inputs.wiki-path }}
        ignore: ${{ inputs.ignore-file }}

    - name: ðŸ“ Generate summary
      if: always()
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## ðŸ“š Wiki Sync Summary
        
        | Property | Value |
        |:---------|:------|
        | ðŸ“ Source | \`${{ inputs.wiki-path }}\` |
        | ðŸ”„ Status | âœ… Synced |
        
        ---
        
        <sub>ðŸ¤– Powered by github-wiki-action</sub>
        EOF
