# ============================================================================
# ðŸš€ Semantic Release Action
# ============================================================================
# Reusable composite action for automated semantic versioning and releases.
# Generates changelogs, bumps versions, and creates GitHub releases.
#
# Usage:
#   - uses: fulviofreitas/eero-api/.github/actions/semantic-release@master
#     with:
#       github-token: ${{ secrets.GITHUB_TOKEN }}
# ============================================================================

name: "ðŸš€ Semantic Release"
description: "Run semantic-release for automated versioning"

inputs:
  github-token:
    description: "GitHub token for creating releases"
    required: true
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  dry-run:
    description: "Run in dry-run mode"
    required: false
    default: "false"
  extra-plugins:
    description: "Additional semantic-release plugins (comma-separated)"
    required: false
    default: ""

outputs:
  released:
    description: "Whether a release was created"
    value: ${{ steps.check-release.outputs.released }}
  version:
    description: "Released version (if any)"
    value: ${{ steps.check-release.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: ðŸ“¦ Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: ðŸ”§ Install semantic-release
      shell: bash
      run: |
        npm install -g \
          semantic-release@24 \
          @semantic-release/changelog@6 \
          @semantic-release/git@10 \
          @semantic-release/exec@6 \
          conventional-changelog-conventionalcommits@8
        
        # Install extra plugins if specified
        if [ -n "${{ inputs.extra-plugins }}" ]; then
          echo "Installing extra plugins: ${{ inputs.extra-plugins }}"
          npm install -g $(echo "${{ inputs.extra-plugins }}" | tr ',' ' ')
        fi

    - name: ðŸ“‹ Capture current version
      id: before
      shell: bash
      run: |
        if [ -f VERSION ]; then
          CURRENT_VERSION=$(cat VERSION)
          echo "version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
          echo "ðŸ“Œ Current version: v${CURRENT_VERSION}"
        else
          echo "version=" >> $GITHUB_OUTPUT
          echo "ðŸ“Œ No VERSION file found"
        fi

    - name: ðŸš€ Run semantic-release
      id: release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          echo "ðŸ§ª Running in dry-run mode..."
          semantic-release --dry-run
        else
          semantic-release
        fi

    - name: ðŸ” Check if release was created
      id: check-release
      shell: bash
      run: |
        BEFORE_VERSION="${{ steps.before.outputs.version }}"
        
        if [ -f VERSION ]; then
          AFTER_VERSION=$(cat VERSION)
          
          if [ "$BEFORE_VERSION" != "$AFTER_VERSION" ]; then
            echo "released=true" >> $GITHUB_OUTPUT
            echo "version=${AFTER_VERSION}" >> $GITHUB_OUTPUT
            echo "âœ… New release: v${BEFORE_VERSION} â†’ v${AFTER_VERSION}"
          else
            echo "released=false" >> $GITHUB_OUTPUT
            echo "version=" >> $GITHUB_OUTPUT
            echo "ðŸ“­ No version change (still v${AFTER_VERSION})"
          fi
        else
          echo "released=false" >> $GITHUB_OUTPUT
          echo "version=" >> $GITHUB_OUTPUT
          echo "ðŸ“­ No VERSION file found"
        fi

    - name: ðŸ“ Generate release summary
      if: always()
      shell: bash
      run: |
        DRY_RUN="${{ inputs.dry-run }}"
        RELEASED="${{ steps.check-release.outputs.released }}"
        NEW_VERSION="${{ steps.check-release.outputs.version }}"
        OLD_VERSION="${{ steps.before.outputs.version }}"
        
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ## ðŸš€ Release Summary
        
        EOF
        
        if [ "$DRY_RUN" = "true" ]; then
          cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        > [!NOTE]
        > ### ðŸ§ª Dry-Run Mode
        > No actual release was created.
        
        EOF
        fi
        
        if [ "$RELEASED" = "true" ] && [ -n "$NEW_VERSION" ]; then
          if [ "$DRY_RUN" = "true" ]; then
            cat >> $GITHUB_STEP_SUMMARY << EOF
        ### ðŸ“‹ Would Release
        
        | Property | Value |
        |:---------|:------|
        | ðŸ·ï¸ Previous | \`v${OLD_VERSION}\` |
        | ðŸ·ï¸ New | \`v${NEW_VERSION}\` |
        
        EOF
          else
            cat >> $GITHUB_STEP_SUMMARY << EOF
        > [!TIP]
        > ### âœ… Release Created Successfully
        > Version \`v${NEW_VERSION}\` has been published!
        
        | Property | Value |
        |:---------|:------|
        | ðŸ·ï¸ Previous | \`v${OLD_VERSION}\` |
        | ðŸ·ï¸ New | \`v${NEW_VERSION}\` |
        | ðŸ”— Release | [View Release](../../releases/tag/v${NEW_VERSION}) |
        
        EOF
          fi
        else
          cat >> $GITHUB_STEP_SUMMARY << EOF
        > [!NOTE]
        > ### ðŸ“­ No Release Created
        > No releasable changes detected (current version: v${OLD_VERSION}).
        >
        > Use [Conventional Commits](https://conventionalcommits.org):
        > - \`feat:\` â†’ Minor release
        > - \`fix:\` â†’ Patch release
        > - \`feat!:\` â†’ Major release
        
        EOF
        fi
